Puestos de Trabajo/Controllers/PuestoTrabajoesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Puestos_de_Trabajo.Models;
using System.Web.Security;
using Microsoft.AspNet.Identity;

namespace Puestos_de_Trabajo.Controllers
{
    public class PuestoTrabajoesController : Controller
    {
        private PuestosEntities db = new PuestosEntities();

        // GET: PuestoTrabajoes
        public ActionResult Index(String cargo)
        {
            var puestoTrabajo = from s in db.PuestoTrabajo select s;

            if (!String.IsNullOrEmpty(cargo))
    	    {
                puestoTrabajo = puestoTrabajo.Where(j => j.cargo.Contains(cargo));
            }
            return View(puestoTrabajo);
        }
    

        // GET: PuestoTrabajoes/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PuestoTrabajo puestoTrabajo = await db.PuestoTrabajo.FindAsync(id);
            if (puestoTrabajo == null)
            {
                return HttpNotFound();
            }
            return View(puestoTrabajo);
        }

        // GET: PuestoTrabajoes/Create
        [Authorize(Roles = "Administrator, Poster")]
        public ActionResult Create()
        {
            PuestoTrabajo puesto = new PuestoTrabajo();
            puesto.estado = "Activo";
            puesto.fecha_Publicacion = DateTime.Now;
            ViewBag.tipo = new SelectList(db.Tipo, "Descripcion", "Descripcion");
            ViewBag.id_Usuario = new SelectList(db.AspNetUsers, "Id", "Email");
            ViewBag.id_Categoria = new SelectList(db.Categoria, "id", "descripcion");
            ViewBag.id_Empresa = new SelectList(db.Empresa, "id", "nombre");
            return View(puesto);
        }

        // POST: PuestoTrabajoes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator, Poster")]
        public async Task<ActionResult> Create([Bind(Include = "id,id_Empresa,id_Usuario,id_Categoria,url,cargo,estado,fecha_Publicacion,tipo,logo,descripcion,publico,dias_trabajo_linea")] PuestoTrabajo puestoTrabajo)
        {
            if (ModelState.IsValid)
            {
                puestoTrabajo.estado = "Activo";
                puestoTrabajo.fecha_Publicacion = DateTime.Now;
                puestoTrabajo.id_Usuario = User.Identity.GetUserId();
                db.PuestoTrabajo.Add(puestoTrabajo);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.tipo = new SelectList(db.Tipo, "Descripcion", "Descripcion", puestoTrabajo.tipo);
            ViewBag.id_Usuario = new SelectList(db.AspNetUsers, "Id", "Email", puestoTrabajo.id_Usuario);
            ViewBag.id_Categoria = new SelectList(db.Categoria, "id", "descripcion", puestoTrabajo.id_Categoria);
            ViewBag.id_Empresa = new SelectList(db.Empresa, "id", "nombre", puestoTrabajo.id_Empresa);
            return View(puestoTrabajo);
        }

        // GET: PuestoTrabajoes/Edit/5
        [Authorize(Roles = "Administrator, Affilliate")]
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PuestoTrabajo puestoTrabajo = await db.PuestoTrabajo.FindAsync(id);
            if (puestoTrabajo == null)
            {
                return HttpNotFound();
            }
            ViewBag.tipo = new SelectList(db.Tipo, "Descripcion", "Descripcion", puestoTrabajo.tipo);
            ViewBag.id_Usuario = new SelectList(db.AspNetUsers, "Id", "Email", puestoTrabajo.id_Usuario);
            ViewBag.id_Categoria = new SelectList(db.Categoria, "id", "descripcion", puestoTrabajo.id_Categoria);
            ViewBag.id_Empresa = new SelectList(db.Empresa, "id", "nombre", puestoTrabajo.id_Empresa);
            return View(puestoTrabajo);
        }

        // POST: PuestoTrabajoes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator, Affilliate")]
        public async Task<ActionResult> Edit([Bind(Include = "id,id_Empresa,id_Usuario,id_Categoria,url,cargo,estado,fecha_Publicacion,tipo,logo,descripcion,publico,dias_trabajo_linea")] PuestoTrabajo puestoTrabajo)
        {
            if (ModelState.IsValid)
            {
                db.Entry(puestoTrabajo).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.tipo = new SelectList(db.Tipo, "Descripcion", "Descripcion", puestoTrabajo.tipo);
            ViewBag.id_Usuario = new SelectList(db.AspNetUsers, "Id", "Email", puestoTrabajo.id_Usuario);
            ViewBag.id_Categoria = new SelectList(db.Categoria, "id", "descripcion", puestoTrabajo.id_Categoria);
            ViewBag.id_Empresa = new SelectList(db.Empresa, "id", "nombre", puestoTrabajo.id_Empresa);
            return View(puestoTrabajo);
        }

        // GET: PuestoTrabajoes/Delete/5

        [Authorize(Roles = "Administrator")]
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PuestoTrabajo puestoTrabajo = await db.PuestoTrabajo.FindAsync(id);
            if (puestoTrabajo == null)
            {
                return HttpNotFound();
            }
            return View(puestoTrabajo);
        }

        [Authorize(Roles = "Administrator")]
        // POST: PuestoTrabajoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            PuestoTrabajo puestoTrabajo = await db.PuestoTrabajo.FindAsync(id);
            db.PuestoTrabajo.Remove(puestoTrabajo);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Puestos de Trabajo/Views/PuestoTrabajoes/Create.cshtml
@model Puestos_de_Trabajo.Models.PuestoTrabajo

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Puesto de Trabajo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.id_Empresa, "Empresa", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("id_Empresa", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.id_Empresa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.id_Categoria, "Categoría", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("id_Categoria", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.id_Categoria, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.url, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.url, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.url, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cargo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cargo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cargo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
             @Html.LabelFor(model => model.logo, htmlAttributes: new { @class = "control-label col-md-2" })
             <div class="col-md-10">
                  <input type="file" name="logo" />
             </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.publico, "Público", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.publico)
                    @Html.ValidationMessageFor(model => model.publico, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.tipo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("tipo", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.tipo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dias_trabajo_linea, "Días de Trabajo en Línea", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dias_trabajo_linea, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dias_trabajo_linea, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Puestos de Trabajo/Views/PuestoTrabajoes/Delete.cshtml
@model Puestos_de_Trabajo.Models.PuestoTrabajo

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PuestoTrabajo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.url)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.url)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cargo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cargo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.estado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fecha_Publicacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fecha_Publicacion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tipo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tipo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.logo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.logo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.publico)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.publico)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dias_trabajo_linea)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dias_trabajo_linea)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AspNetUsers.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AspNetUsers.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Categoria.descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Categoria.descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Empresa.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Empresa.nombre)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Puestos de Trabajo/Views/PuestoTrabajoes/Details.cshtml
@model Puestos_de_Trabajo.Models.PuestoTrabajo

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Puesto de Trabajo</h4>
    <hr />
    <dl class="dl-horizontal jumbotron">
        <dt>
            @Html.DisplayNameFor(model => model.url)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.url)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cargo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cargo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.estado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fecha_Publicacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fecha_Publicacion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tipo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tipo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.logo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.logo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.publico)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.publico)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dias_trabajo_linea)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dias_trabajo_linea)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AspNetUsers.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AspNetUsers.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Categoria.descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Categoria.descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Empresa.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Empresa.nombre)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Puestos de Trabajo/Views/PuestoTrabajoes/Edit.cshtml
@model Puestos_de_Trabajo.Models.PuestoTrabajo

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PuestoTrabajo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.id_Empresa, "id_Empresa", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("id_Empresa", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.id_Empresa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.id_Usuario, "id_Usuario", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("id_Usuario", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.id_Usuario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.id_Categoria, "id_Categoria", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("id_Categoria", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.id_Categoria, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.url, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.url, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.url, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cargo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cargo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cargo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.estado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.estado, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.estado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fecha_Publicacion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fecha_Publicacion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fecha_Publicacion, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.tipo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("tipo", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.tipo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.logo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.logo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.logo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.publico, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.publico)
                    @Html.ValidationMessageFor(model => model.publico, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dias_trabajo_linea, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dias_trabajo_linea, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dias_trabajo_linea, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Puestos de Trabajo/Views/PuestoTrabajoes/Index.cshtml
@model IEnumerable<Puestos_de_Trabajo.Models.PuestoTrabajo>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
    <h2>Puestos de Trabajo</h2>

                      <p>
                          <a href="~/PuestoTrabajoes/Create">
                              <button class="btn btn-default">
                                  Postear un Trabajo
                              </button>
                          </a>
                      </p>


    <p>
        @using (Html.BeginForm("Index","PuestoTrabajoes",FormMethod.Get))
        {
            <p>
                Búsquedas por Cargo: @Html.TextBox("cargo") 
                <input type="submit" value="Buscar" />
            </p>
        }
    </p>

    <table class="table table-striped">
        <tr>
            <td>
                <b>Categoría</b>
            </td>
            <td>
                <b>Cargo</b>
            </td>
            <td>
                <b>Descripción</b>
            </td>
            <td> 
                <b>Compañía</b>
            </td>
            <td>
                <b>Localidad</b>
            </td>
            <td></td>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Categoria.descripcion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.cargo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.descripcion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Empresa.nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Empresa.localidad)
                </td>
                <td>
                    <a class="btn btn-primary glyphicon glyphicon-pencil" @Html.ActionLink("Edit", "Edit", new { id = item.id }) |
                    <a class="btn btn-success glyphicon glyphicon-eye-open" @Html.ActionLink("Details", "Details", new { id = item.id }) |
                     <a class="btn btn-danger glyphicon glyphicon-trash"  @Html.ActionLink("Delete", "Delete", new { id = item.id })
                </td>
            </tr>
        }

    </table>